CREATE LOGIN WebClient WITH PASSWORD = '123456789';

CREATE DATABASE phonebook;

USE phonebook
GRANT INSERT ON SCHEMA :: dbo TO WebClient;
GRANT SELECT ON SCHEMA :: dbo TO WebClient;
GRANT ALTER ON SCHEMA :: dbo TO WebClient;
GRANT UPDATE ON SCHEMA :: dbo TO WebClient;
GRANT DELETE ON SCHEMA :: dbo TO WebClient;


CREATE TABLE persons(
	id INT PRIMARY KEY IDENTITY NOT NULL ,
	name NVARCHAR(70) NOT NULL,
	number NVARCHAR(20) NOT NULL
);
